[package]
name = "tiberiusdemo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18.1", features = ["full"] }
tokio-util = { version = "0.7.1", features= ["compat"] }
tiberius = { version = "0.9.0", features = ["all"] }
